/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codechallenges;


import org.junit.Test;

import static org.junit.Assert.assertTrue;

class LibraryTest {
    @Test
    void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
